"use client"
import Header from '@/components/client/header'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/client/footer'
import StyledComponentsRegistry from '@/lib/AntdRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Client({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className=''>
      <Header />
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      <Footer />
    </div>
  )
}
